### ISSUE TITLE
Is the CSV results file from the corrected IEEE spreadsheet or the original?

### ISSUE THREAD

**Issue by jgrimard** [LiaungYip/arcflash#3]
Hello @LiaungYip 
Very nice work here.
Are the CSV results you posted from the "corrected" spreadsheet or the original spreadsheet with the wrong formulas?
Could you upload both if you have them still?

[arcflash/ieee_1584/additional_test_cases/ieee_1584_spreadsheet_results.csv](https://github.com/LiaungYip/arcflash/blob/main/arcflash/ieee_1584/additional_test_cases/ieee_1584_spreadsheet_results.csv)

Thank you,
JGrimard

**Comment by LiaungYip** [comment]
This will be the results from the corrected spreadsheet.

The reason I calculated the spreadsheet results was to check the Python
code using a different calculation implementation. Only correct results
were useful for that purpose.

I didn't retain the results from the erroneous spreadsheet.

**Comment by jgrimard** [comment]
Thank you for the fast response.  I don't actually need the erroneous results.  I just wanted to use the correct results to run some tests on my Javascript implementation of the IEEE calculations that I'm working on but I wasn't sure if the results were from the corrected version or not.  Now I know they are correct.
Have a great day.

**Comment by LiaungYip** [comment]
If you are testing a JavaScript project you can generate many more test
cases - I had to scale back the number of tests I did because Excel is very
slow. There should be some test case generation code in this repository.

**Comment by jgrimard** [comment]
I am going to use the CSV file to validate that my JavaScript implementation is producing the correct results.  It is perfect for what I need.  144,000 test cases is much better than the two test cases provided in the IEEE calculations.
